#!/usr/bin/env python3
"""Export the Lucide (ISC) paths supplied with the v2 reference as Android vectors."""
from pathlib import Path
import re
import sys
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'design/reference/ol-icons.js'
DRAWABLES = ROOT / 'app/src/main/res/drawable'


def path_data(node):
    a = node.attrib
    if node.tag == 'path':
        return a['d']
    if node.tag == 'line':
        return f"M{a['x1']} {a['y1']} L{a['x2']} {a['y2']}"
    if node.tag == 'polyline':
        return 'M' + a['points']
    if node.tag == 'circle':
        x, y, r = (float(a[k]) for k in ('cx', 'cy', 'r'))
        return f'M{x-r:g} {y:g} a{r:g} {r:g} 0 1 0 {2*r:g} 0 a{r:g} {r:g} 0 1 0 {-2*r:g} 0'
    if node.tag == 'rect':
        x, y = float(a.get('x', 0)), float(a.get('y', 0))
        w, h = float(a['width']), float(a['height'])
        rx = min(float(a.get('rx', a.get('ry', 0))), w / 2)
        ry = min(float(a.get('ry', a.get('rx', 0))), h / 2)
        return (f'M{x+rx:g} {y:g} H{x+w-rx:g} A{rx:g} {ry:g} 0 0 1 {x+w:g} {y+ry:g} '
                f'V{y+h-ry:g} A{rx:g} {ry:g} 0 0 1 {x+w-rx:g} {y+h:g} '
                f'H{x+rx:g} A{rx:g} {ry:g} 0 0 1 {x:g} {y+h-ry:g} '
                f'V{y+ry:g} A{rx:g} {ry:g} 0 0 1 {x+rx:g} {y:g} Z')
    raise ValueError(f'Unsupported SVG element: {node.tag}')


def main():
    icons = dict(re.findall(r"    '([^']+)': '([^']+)'", SOURCE.read_text()))
    used = set()
    for file in (ROOT / 'app/src/main').rglob('*'):
        if file.suffix in {'.kt', '.xml'}:
            used.update(re.findall(r'ic_ol_([a-z_0-9]+)', file.read_text()))
    for name in sorted(used):
        svg = ET.fromstring('<svg>' + icons[name.replace('_', '-')] + '</svg>')
        mirror = ' android:autoMirrored="true"' if name == 'arrow_left' else ''
        paths = ''.join(
            f'    <path android:strokeColor="@color/icon_mask" android:strokeWidth="2" '
            f'android:strokeLineCap="round" android:strokeLineJoin="round" android:pathData="{path_data(node)}" />\n'
            for node in svg
        )
        vector = (
            '<?xml version="1.0" encoding="utf-8"?>\n<!-- Lucide, ISC; generated by tools/export_ui_icons.py. -->\n'
            '<vector xmlns:android="http://schemas.android.com/apk/res/android" '
            f'android:width="24dp" android:height="24dp" android:viewportWidth="24" android:viewportHeight="24"{mirror}>\n'
            + paths + '</vector>\n'
        )
        destination = DRAWABLES / f'ic_ol_{name}.xml'
        if '--check' in sys.argv:
            assert destination.read_text() == vector, f'Stale vector: {name}'
        else:
            destination.write_text(vector)
    print(f"{'Verified' if '--check' in sys.argv else 'Exported'} {len(used)} Open Line UI icons")


if __name__ == '__main__':
    main()
